name = "DistributedData"
uuid = "f6a0035f-c5ac-4ad0-b410-ad102ced35df"
authors = ["Mirek Kratochvil <miroslav.kratochvil@uni.lu>",
           "LCSB R3 team <lcsb-r3@uni.lu>"]
version = "0.1.1"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
